name: KitPreview
main: com.seaneoconnor.kitpreview.KitPreview
version: 3.5.0
depend: [Essentials]
description: View a kit before you purchase it!
author: Rega
website: https://www.seaneoconnor.com/
commands:
  kitpreview:
    description: View information on this plugin.
    default: true
    aliases: [kp]
    usage: /<command> [reload]
  previewkit:
    description: Preview a kit
    default: true
    aliases: [pk, preview]
    usage: /<command> [kit]